/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.io.File;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class CreateMarketingProject extends javax.swing.JFrame {

    /**
     * Creates new form CreateMarketingProject
     */
    public CreateMarketingProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProjectName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        btnAddStaff = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnHomepage = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        txtBudget = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        txtTargetAudience = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(190, 209, 207));

        jPanel2.setBackground(new java.awt.Color(255, 247, 241));

        jLabel1.setFont(new java.awt.Font("STLiti", 1, 24)); // NOI18N
        jLabel1.setText("Create New Marketing Project");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel2.setText("Enter Project Name");

        jLabel3.setText("Enter Project Description");

        jLabel4.setText("Enter Start Date (YYYY-MM-DD)");

        jLabel5.setText("Enter End date (YYYY-MM-DD)");

        jLabel6.setText("Enter Budget (RM)");

        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Staff Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblStaff);
        if (tblStaff.getColumnModel().getColumnCount() > 0) {
            tblStaff.getColumnModel().getColumn(0).setResizable(false);
            tblStaff.getColumnModel().getColumn(1).setResizable(false);
        }

        btnAddStaff.setText("Add");
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnHomepage.setText("Homepage");
        btnHomepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomepageActionPerformed(evt);
            }
        });

        jLabel7.setText("Select Staff to work on this project");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel8.setText("Enter Target Audience");

        txtDescription.setColumns(20);
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtDescription);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProjectName)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtBudget)
                    .addComponent(jLabel8)
                    .addComponent(txtEndDate)
                    .addComponent(txtStartDate)
                    .addComponent(txtTargetAudience)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddStaff)
                                .addGap(49, 49, 49))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(59, 59, 59)
                                .addComponent(btnCreate)
                                .addGap(41, 41, 41)))
                        .addComponent(btnHomepage)
                        .addGap(79, 79, 79))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTargetAudience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreate)
                            .addComponent(btnBack)
                            .addComponent(btnHomepage))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddStaff)
                        .addGap(76, 76, 76))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ProjectDashboard project = new ProjectDashboard();
        project.setVisible(true);
        project.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomepageActionPerformed
        ManagerHomepage home = new ManagerHomepage();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnHomepageActionPerformed

    ArrayList<Scheduler> schedulerAssigned = new ArrayList();
    
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if ("".equals(txtProjectName.getText())){
            JOptionPane.showMessageDialog(null, "Enter a Project Name.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtProjectName.requestFocusInWindow();
        }
        else if ("".equals(txtDescription.getText())){
            JOptionPane.showMessageDialog(null, "Enter a Project Description.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtDescription.requestFocusInWindow();
        }
        else if ("".equals(txtStartDate.getText())){
            JOptionPane.showMessageDialog(null, "Enter a Start Date first.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtStartDate.requestFocusInWindow();
        }
        else if(!Project.validDateFormat(txtStartDate.getText())){
            JOptionPane.showMessageDialog(null, "Start Date format is invalid.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtStartDate.setText("");  
            txtStartDate.requestFocusInWindow();
        }
        else if(!Project.validFutureDate(txtStartDate.getText())){
            JOptionPane.showMessageDialog(null, "Start Date cannot be today or a past date.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtStartDate.setText("");  
            txtStartDate.requestFocusInWindow();
        }
        else if ("".equals(txtEndDate.getText())){
            JOptionPane.showMessageDialog(null, "Enter an End Date first.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtEndDate.requestFocusInWindow();
        }
        else if(!Project.validDateFormat(txtEndDate.getText())){
            JOptionPane.showMessageDialog(null, "End Date format is invalid.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtEndDate.setText("");  
            txtEndDate.requestFocusInWindow();
        }
        else if(!Project.validFutureDate(txtEndDate.getText())){
            JOptionPane.showMessageDialog(null, "End Date cannot be today or a past date.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtEndDate.setText("");  
            txtEndDate.requestFocusInWindow();
        }
        else if(!Project.endDateAfterStart(txtEndDate.getText(), txtStartDate.getText())){
            JOptionPane.showMessageDialog(null, "End Date cannot be before Start Date.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtEndDate.setText("");  
            txtEndDate.requestFocusInWindow();
        }
        else if ("".equals(txtTargetAudience.getText())){ // validation for not entering TargetAudience
            JOptionPane.showMessageDialog(null, "Enter a Target Audience first.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtTargetAudience.requestFocusInWindow();
        }
        else if("".equals(txtBudget.getText())){
            JOptionPane.showMessageDialog(null, "Enter a Budget first.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtBudget.requestFocusInWindow();
        }
        else if (!Project.validBudget(txtBudget.getText())){
            JOptionPane.showMessageDialog(null, "Invalid Budget amount entered.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtBudget.setText("");
            txtBudget.requestFocusInWindow();
        }
        else if (schedulerAssigned.isEmpty()){
            JOptionPane.showMessageDialog(null, "Add Staff to work on this project first.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            String status = createProject();
            JOptionPane.showMessageDialog(null, status, "Information", JOptionPane.INFORMATION_MESSAGE);
            txtProjectName.setText("");
            txtDescription.setText("");
            txtStartDate.setText("");
            txtEndDate.setText("");
            txtTargetAudience.setText("");
            txtBudget.setText("");
            schedulerAssigned.clear();
        }     
    }//GEN-LAST:event_btnCreateActionPerformed

    // method to create project
    private String createProject(){
        String projectID = Project.generateUniqueProjectID("MarketingProjects.txt", "MarketingProject");
        double amount = Double.parseDouble(txtBudget.getText());
        
        MarketingProject newProject = new MarketingProject(projectID, txtProjectName.getText(), txtDescription.getText(), txtStartDate.getText(), 
                txtEndDate.getText(), amount, schedulerAssigned, txtTargetAudience.getText());
        ArrayList<MarketingProject> projects = new ArrayList();
        projects.add(newProject);
        FileOperations file = new FileOperations();
        
        String status = file.writeToFile("MarketingProjects.txt", projects);
        
        return status;
        
    }
    
    
    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
        int selectedRow = tblStaff.getSelectedRow();
        if (selectedRow != -1){
            String selectedStaffID = tblStaff.getValueAt(selectedRow, 0).toString();
            String selectedStaffName = tblStaff.getValueAt(selectedRow, 1).toString();
            
            Scheduler staff = new Scheduler(selectedStaffID, selectedStaffName);//checking if alaredy added to arrayList
            if (schedulerAssigned.contains(staff)){
                JOptionPane.showMessageDialog(null, "This Staff has already been added to work on this project.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                File checkFile = new File("MarketingProjects.txt");
                if (!checkFile.exists()) { //checking if file does not exist - if does not exist, no project containg the current staff object
                    schedulerAssigned.add(staff);
                }
                else{
                    if(checkAvailabilityOfStaff(staff)){ //if there is a file - checking for staff in other projects
                        schedulerAssigned.add(staff);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Staff is working on another project. Please choose another Staff.", "Information", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Select a StaffID first.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddStaffActionPerformed

    private boolean checkAvailabilityOfStaff(Scheduler scheduler){
        FileOperations file = new FileOperations();
        ArrayList<Casting> array = file.readFile("MarketingProjects.txt");

        if (array == null || array.isEmpty()) {
            return true;
        }

        Casting casting = new Casting();
        ArrayList<Object> projects = casting.convertRecordsToObjects(array, "MarketingProject");

        if (projects == null || projects.isEmpty()) {
            return true;
        }

        ArrayList<MarketingProject> marketingProjects = new ArrayList<>();
        for (Object obj : projects) {
            if (obj instanceof MarketingProject marketingProject) {
                marketingProjects.add(marketingProject);
            } else {
                JOptionPane.showMessageDialog(null, "Unexpected object type: " + obj.getClass().getName(), "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }

        for (MarketingProject project : marketingProjects) {
            if (project.getSchedulers().contains(scheduler)) {
                return false; 
            }
        }
        return true; 
    }
    

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ArrayList<Scheduler> schedulers = Project.schedulerLoader();
        DefaultTableModel table = (DefaultTableModel) tblStaff.getModel();
        for (Scheduler i : schedulers) {
            table.addRow(new Object[]{
                i.getId(),
                i.getName()
            });
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateMarketingProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateMarketingProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateMarketingProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateMarketingProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateMarketingProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnHomepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtProjectName;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTargetAudience;
    // End of variables declaration//GEN-END:variables
}
