/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.io.File;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class CreateConstructionProject extends javax.swing.JFrame {

    /**
     * Creates new form CreateConstructionProject
     */
    public CreateConstructionProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProjectName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContractor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtConstructionSite = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBudget = new javax.swing.JTextField();
        btnAddStaff = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnHomepage = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(190, 209, 207));

        jPanel2.setBackground(new java.awt.Color(255, 247, 241));

        jLabel1.setFont(new java.awt.Font("STLiti", 1, 24)); // NOI18N
        jLabel1.setText("Create New Construction Project");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setText("Enter Project Name");

        jLabel3.setText("Enter Project Description");

        jLabel4.setText("Enter  Start date (YYYY-MM-DD)");

        jLabel5.setText("Enter End Date (YYYY-MM-DD)");

        jLabel6.setText("Enter Construction Site Details");

        txtDescription.setColumns(20);
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescription);

        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Staff Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblStaff);
        if (tblStaff.getColumnModel().getColumnCount() > 0) {
            tblStaff.getColumnModel().getColumn(0).setResizable(false);
            tblStaff.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel7.setText("Enter Contractor");

        jLabel8.setText("Enter Budget (RM)");

        btnAddStaff.setText("Add");
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnHomepage.setText("Homepage");
        btnHomepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomepageActionPerformed(evt);
            }
        });

        jLabel9.setText("Select Staff to work on this project");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(txtProjectName)
                            .addComponent(txtStartDate)
                            .addComponent(txtEndDate)
                            .addComponent(txtConstructionSite)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddStaff)
                                .addGap(54, 54, 54))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtContractor, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(txtBudget))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack)
                                .addGap(67, 67, 67)
                                .addComponent(btnCreate)
                                .addGap(45, 45, 45)))
                        .addComponent(btnHomepage)
                        .addGap(79, 79, 79))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConstructionSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContractor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddStaff))
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack)
                    .addComponent(btnCreate)
                    .addComponent(btnHomepage))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomepageActionPerformed
        ManagerHomepage home = new ManagerHomepage();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnHomepageActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ProjectDashboard project = new ProjectDashboard();
        project.setVisible(true);
        project.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    ArrayList<Scheduler> schedulerAssigned = new ArrayList();// creating Scheduler ArrayList to add schedulers
    
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if ("".equals(txtProjectName.getText())){ // validation for not entering project name
            JOptionPane.showMessageDialog(null, "Enter a Project Name.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtProjectName.requestFocusInWindow();
        }
        else if ("".equals(txtDescription.getText())){ // validation for not entering a project description
            JOptionPane.showMessageDialog(null, "Enter a Project Description.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtDescription.requestFocusInWindow();
        }
        else if ("".equals(txtStartDate.getText())){ // validation for not entering start date
            JOptionPane.showMessageDialog(null, "Enter a Start Date first.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtStartDate.requestFocusInWindow();
        }
        else if(!Project.validDateFormat(txtStartDate.getText())){ // validation for correct format of start date entered
            JOptionPane.showMessageDialog(null, "Start Date format is invalid.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtStartDate.setText("");  
            txtStartDate.requestFocusInWindow();
        }
        else if(!Project.validFutureDate(txtStartDate.getText())){ // validating that start date is in the future
            JOptionPane.showMessageDialog(null, "Start Date cannot be today or a past date.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtStartDate.setText("");  
            txtStartDate.requestFocusInWindow();
        }
        else if ("".equals(txtEndDate.getText())){ // validation for not entering end date
            JOptionPane.showMessageDialog(null, "Enter an End Date first.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtEndDate.requestFocusInWindow();
        }
        else if(!Project.validDateFormat(txtEndDate.getText())){ // validation for correct format of end date
            JOptionPane.showMessageDialog(null, "End Date format is invalid.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtEndDate.setText("");  
            txtEndDate.requestFocusInWindow();
        }
        else if(!Project.validFutureDate(txtEndDate.getText())){ // validating that end date is in the future
            JOptionPane.showMessageDialog(null, "End Date cannot be today or a past date.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtEndDate.setText("");  
            txtEndDate.requestFocusInWindow();
        }
        else if(!Project.endDateAfterStart(txtEndDate.getText(), txtStartDate.getText())){ // validating that end date is after start date
            JOptionPane.showMessageDialog(null, "End Date cannot be before Start Date.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtEndDate.setText("");  
            txtEndDate.requestFocusInWindow();
        }
        else if ("".equals(txtConstructionSite.getText())){ // validation for not entering construction site
            JOptionPane.showMessageDialog(null, "Enter the Construction Site Details first.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtConstructionSite.requestFocusInWindow();
        }
        else if ("".equals(txtContractor.getText())){ // validation for not entering contractor name
            JOptionPane.showMessageDialog(null, "Enter the Contractor first.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtContractor.requestFocusInWindow();
        }
        else if("".equals(txtBudget.getText())){ // validation for not entering budget
            JOptionPane.showMessageDialog(null, "Enter a Budget first.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtBudget.requestFocusInWindow();
        }
        else if (!Project.validBudget(txtBudget.getText())){ // validation for not entering budget in a double format
            JOptionPane.showMessageDialog(null, "Invalid Budget amount entered.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtBudget.setText("");
            txtBudget.requestFocusInWindow();
        }
        else if (schedulerAssigned.isEmpty()){ // validation to check if staffs were assigned
            JOptionPane.showMessageDialog(null, "Add Staff to work on this project first.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            String status = createProject(); // creating project
            JOptionPane.showMessageDialog(null, status, "Information", JOptionPane.INFORMATION_MESSAGE);
            
            // clearing everything for next project created
            txtProjectName.setText("");
            txtDescription.setText("");
            txtStartDate.setText("");
            txtEndDate.setText("");
            txtConstructionSite.setText("");
            txtContractor.setText("");
            txtBudget.setText("");
            schedulerAssigned.clear();
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    // method to create project 
    private String createProject(){
        String projectID = Project.generateUniqueProjectID("ConstructionProjects.txt", "ConstructionProject"); // generating the unique project ID
        double amount = Double.parseDouble(txtBudget.getText()); // parsing the budget entered to double
    
        // creating new construction project constructor
        ConstructionProject newProject = new ConstructionProject(projectID, txtProjectName.getText(), txtDescription.getText(), txtStartDate.getText(), txtEndDate.getText(), amount, schedulerAssigned, txtConstructionSite.getText(), txtContractor.getText());
        ArrayList<ConstructionProject> projects = new ArrayList(); // creating ArrayList as writeToFile method take an ArrayList as paramtere
        projects.add(newProject); // adding the project to the ArrayList
        
        FileOperations file = new FileOperations();
        String status = file.writeToFile("ConstructionProjects.txt", projects); // writing the construction project to file
        
        return status; 
        
    }
    
    // method to check availability of staff
    private boolean checkAvailabilityOfStaff(Scheduler scheduler){
        FileOperations file = new FileOperations();
        ArrayList<Casting> array = file.readFile("ConstructionProjects.txt"); // reading the text file

        if (array == null || array.isEmpty()) { // if the file is empty - no projects yet - staff is available
            return true;
        }

        Casting casting = new Casting();
        ArrayList<Object> projects = casting.convertRecordsToObjects(array, "ConstructionProject");

        if (projects == null || projects.isEmpty()) { // if there are no constrcution projects - staff is available
            return true;
        }

        // adding ConstructionProject object to the ArrayList created
        ArrayList<ConstructionProject> constructionProjects = new ArrayList<>();
        for (Object obj : projects) {
            if (obj instanceof ConstructionProject constructionProject) {
                constructionProjects.add(constructionProject);
            } else {
                JOptionPane.showMessageDialog(null, "Unexpected object type: " + obj.getClass().getName(), "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }

        // looping through ConstructionProject object 
        // checking if scheduler object is in the ConstructionProject
        for (ConstructionProject project : constructionProjects) {
            if (project.getSchedulers().contains(scheduler)) {// if the project contains the scheduler object, returning false
                return false; 
            }
        }
        return true; 
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ArrayList<Scheduler> schedulers = Project.schedulerLoader(); //loading schedulers to add to tblStaff
        DefaultTableModel table = (DefaultTableModel) tblStaff.getModel();
        for (Scheduler i : schedulers) {
            table.addRow(new Object[]{ //adding rows
                i.getId(),
                i.getName()
            });
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
        int selectedRow = tblStaff.getSelectedRow();
        if (selectedRow != -1){ // if a row has been selected
            String selectedStaffID = tblStaff.getValueAt(selectedRow, 0).toString();
            String selectedStaffName = tblStaff.getValueAt(selectedRow, 1).toString();
            
            Scheduler staff = new Scheduler(selectedStaffID, selectedStaffName);//checking if already added to arrayList
            if (schedulerAssigned.contains(staff)){
                JOptionPane.showMessageDialog(null, "This Staff has already been added to work on this project.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                File checkFile = new File("ConstructionProjects.txt");
                if (!checkFile.exists()) { //checking if file does not exist - if does not exist, no project contains the current staff object
                    schedulerAssigned.add(staff);
                }
                else{
                    if(checkAvailabilityOfStaff(staff)){ //if there is a file - checking for staff in other projects
                        schedulerAssigned.add(staff);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Staff is working on another project. Please choose another Staff.", "Information", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Select a StaffID first.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateConstructionProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateConstructionProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateConstructionProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateConstructionProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateConstructionProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnHomepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtConstructionSite;
    private javax.swing.JTextField txtContractor;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtProjectName;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
}
