/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class CustomerIssueManagementDB extends javax.swing.JFrame {

    /**
     * Creates new form CustomerIssueManagementDB
     */
    public CustomerIssueManagementDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboStatusFilter = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIssueDescription = new javax.swing.JTextArea();
        btnViewDescription = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnAssignStaff = new javax.swing.JButton();
        btnHomepage = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtReply = new javax.swing.JTextArea();
        btnReply = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboChangeStatus = new javax.swing.JComboBox<>();
        btnChangeStatus = new javax.swing.JButton();
        btnStatusMeaning = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblIssue = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(190, 209, 207));

        jPanel2.setBackground(new java.awt.Color(255, 247, 241));

        jLabel2.setText("Choose Status Filter");

        cboStatusFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Open", "In Progress", "Done", "Closed", "Cancelled" }));
        cboStatusFilter.setSelectedIndex(-1);
        cboStatusFilter.setSelectedItem(null);

        btnFilter.setText("Filter");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        jLabel3.setText("View Complete Issue Description");

        txtIssueDescription.setColumns(20);
        txtIssueDescription.setLineWrap(true);
        txtIssueDescription.setRows(5);
        txtIssueDescription.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtIssueDescription);

        btnViewDescription.setText("View");
        btnViewDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDescriptionActionPerformed(evt);
            }
        });

        jLabel4.setText("Choose Staff to be Assigned");

        btnAssignStaff.setText("Assign");
        btnAssignStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignStaffActionPerformed(evt);
            }
        });

        btnHomepage.setText("Homepage");
        btnHomepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomepageActionPerformed(evt);
            }
        });

        jLabel6.setText("Reply to Issue");

        txtReply.setColumns(20);
        txtReply.setLineWrap(true);
        txtReply.setRows(5);
        txtReply.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtReply);

        btnReply.setText("Reply");
        btnReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplyActionPerformed(evt);
            }
        });

        jLabel7.setText("Change Status");

        cboChangeStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Done", "Closed", "Cancelled" }));
        cboChangeStatus.setSelectedIndex(-1);
        cboChangeStatus.setSelectedItem(null);

        btnChangeStatus.setText("Change");
        btnChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStatusActionPerformed(evt);
            }
        });

        btnStatusMeaning.setText("?");
        btnStatusMeaning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusMeaningActionPerformed(evt);
            }
        });

        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StaffID", "Staff Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStaff);
        if (tblStaff.getColumnModel().getColumnCount() > 0) {
            tblStaff.getColumnModel().getColumn(0).setResizable(false);
            tblStaff.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnStatusMeaning, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilter))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnViewDescription)))
                .addGap(115, 115, 115)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cboChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReply)
                        .addGap(104, 104, 104))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHomepage)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(cboStatusFilter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(150, 150, 150)
                        .addComponent(btnAssignStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChangeStatus)
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cboStatusFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFilter)
                            .addComponent(btnStatusMeaning)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewDescription))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReply)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChangeStatus)
                            .addComponent(btnHomepage)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAssignStaff)
                        .addGap(76, 76, 76)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 247, 241));

        jLabel1.setFont(new java.awt.Font("STLiti", 1, 24)); // NOI18N
        jLabel1.setText("Manage Customer Issues");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tblIssue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IssueID", "Description", "Status", "StaffID", "Staff Name", "Response", "BookingID", "CustomerID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblIssue);
        if (tblIssue.getColumnModel().getColumnCount() > 0) {
            tblIssue.getColumnModel().getColumn(0).setResizable(false);
            tblIssue.getColumnModel().getColumn(1).setResizable(false);
            tblIssue.getColumnModel().getColumn(2).setResizable(false);
            tblIssue.getColumnModel().getColumn(3).setResizable(false);
            tblIssue.getColumnModel().getColumn(4).setResizable(false);
            tblIssue.getColumnModel().getColumn(5).setResizable(false);
            tblIssue.getColumnModel().getColumn(6).setResizable(false);
            tblIssue.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // method to customer issues to rows in the table
    private void addRowsIssues(ArrayList<Casting> array){
        DefaultTableModel table = (DefaultTableModel) tblIssue.getModel();
        table.setRowCount(0);
        Casting cast = new Casting();
        ArrayList<Object> issuesObjects = cast.convertRecordsToObjects(array, "CustomerIssue");
        ArrayList<CustomerIssue> issues = new ArrayList();
        
        // adding CustomerIssue object to the ArrayList
        for (Object obj : issuesObjects) {
            if (obj instanceof CustomerIssue customerIssue) {
                issues.add(customerIssue);
            } 
            else {
                JOptionPane.showMessageDialog(null, "Unexpected object type: " + obj.getClass().getName(), "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
                
        for (CustomerIssue i : issues) {//looping through ArrayList of CustomerIssues
            table.addRow(new Object[]{ //adding rows to the table, accessing attributes using getters
                i.getIssueID(),
                i.getIssueDescription(),
                i.getStatus(),
                i.getStaffID(),
                i.getStaffName(),
                i.getResponse(),
                i.getBookingID(),
                i.getCustomerID()
            });
        } 
    }
    
    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        if (cboStatusFilter.getSelectedIndex() != -1){ // checking if ststus to filter has been selected 
            String status = cboStatusFilter.getSelectedItem().toString(); // getting status
            FileOperations file = new FileOperations();
            ArrayList<Casting> filteredIssues = file.searchRecord("CustomerIssue.txt", status, 2); // searching CustomerIssues that correspond to the status
            if (!filteredIssues.isEmpty()){ // if the ArrayList is not empty - there are CustomerIssues that contain this status 
                addRowsIssues(filteredIssues); // thus adding the filteredIssues to the table
            }
            else{
                JOptionPane.showMessageDialog(null, "There is no customer issue yet under the status: " + status , "Information", JOptionPane.INFORMATION_MESSAGE);
            }

        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a Status first.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnFilterActionPerformed

    // method to load scheduler objects from scheduler.txt
    private ArrayList<Scheduler> schedulerLoader(){
        ArrayList<Scheduler> schedulers = new ArrayList();
        File checkFile = new File("scheduler.txt");
        if (!checkFile.exists()) { //checking if the file exist first
            JOptionPane.showMessageDialog(null, "No scheduler has been added yet.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            FileOperations file = new FileOperations();
            ArrayList<Casting> schedulerRecords = file.readFile("scheduler.txt");
            if (!schedulerRecords.isEmpty()){// check if ArrayList is empty
                Casting cast = new Casting();
                ArrayList<Object> schedulerObjects = cast.convertRecordsToObjects(schedulerRecords, "Scheduler");

                // adding the scheduler objects to the scheduler ArrayList
                for (Object obj : schedulerObjects) {
                    if (obj instanceof Scheduler scheduler) {
                        schedulers.add(scheduler);
                    } 
                    else {
                        JOptionPane.showMessageDialog(null, "Unexpected object type: " + obj.getClass().getName(), "Information", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "No scheduler has been added yet.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        return schedulers;
    }
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        File checkFile = new File("CustomerIssue.txt");
        if (!checkFile.exists()) { // checking if the file exist first
            JOptionPane.showMessageDialog(null, "No Customer Issue has been raised until now.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            FileOperations file = new FileOperations();
            ArrayList<Casting> customerIssues = file.readFile("CustomerIssue.txt"); // file exits - thus reading form the file

            if (!customerIssues.isEmpty()){ // if the ArrayList is not empty - there are CustomerIssues in the file 
                addRowsIssues(customerIssues); // adding the issuse to the table
            }
            else{
                JOptionPane.showMessageDialog(null, "No Customer Issue has been raised until now.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
        //loading the scheduler objects into the tblStaff
        ArrayList<Scheduler> schedulers = schedulerLoader();
        DefaultTableModel table = (DefaultTableModel) tblStaff.getModel();
        for (Scheduler i : schedulers) {
            table.addRow(new Object[]{
                i.getId(),
                i.getName()
            });
        }
    }//GEN-LAST:event_formWindowOpened

    // method to view the full description of the issue selected
    private void btnViewDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDescriptionActionPerformed
        if (tblIssue.getSelectedRow() != -1){
            String description = tblIssue.getValueAt(tblIssue.getSelectedRow(), 1).toString();
            txtIssueDescription.setText(description);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select one IssueId first.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnViewDescriptionActionPerformed

    // method to modify the CustomerIssue object as staff is added 
    private boolean modifyStaff(int rowIssue, int rowStaff){
        // fetching necessary values
        String oldStaffID = tblIssue.getValueAt(rowIssue, 3).toString();
        String oldStaffName = tblIssue.getValueAt(rowIssue, 4).toString();
        String IDValue = tblIssue.getValueAt(rowIssue, 0).toString();
        String newStaffID = tblStaff.getValueAt(rowStaff, 0).toString();
        String newStaffName = tblStaff.getValueAt(rowStaff, 1).toString();
        String oldStatus = tblIssue.getValueAt(rowIssue, 2).toString();
        FileOperations file = new FileOperations();
        
        // modifying scheduler ID, scheduler name and status in CustomerIssue.txt
        // when assigning staff to the issue, the status will automatically be updated to 'In Progress'
        String statusModifyID = file.modify("CustomerIssue.txt", 3, oldStaffID, newStaffID, IDValue, 0);
        String statusModifyName = file.modify("CustomerIssue.txt", 4, oldStaffName, newStaffName, IDValue, 0);
        String statusModifyStatus = file.modify("CustomerIssue.txt", 2, oldStatus, "In Progress", IDValue, 0);
        
        // updating the row in the table if all 3 modifications are successfull
        if ("Record updated successfully.".equals(statusModifyID) && "Record updated successfully.".equals(statusModifyName) && "Record updated successfully.".equals(statusModifyStatus)){
            updateTable(tblIssue, rowIssue, 3, newStaffID);
            updateTable(tblIssue, rowIssue, 4, newStaffName);
            updateTable(tblIssue, rowIssue, 2, "In Progress");
            
            return true; // returning true - modification has succeeded
        }
        else{
            return false; // modifications have failed
        }
    }
    

    private void btnAssignStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignStaffActionPerformed
        int rowIssue = tblIssue.getSelectedRow();
        int rowStaff = tblStaff.getSelectedRow();
        if (rowIssue != -1){ // if issue has been selected
            if (rowStaff != -1){ // if staff has been selected
                String currentStatus = tblIssue.getValueAt(rowIssue, 2).toString(); // retrieving status
                if ("Closed".equals(currentStatus) || "Done".equals(currentStatus) || "Cancelled".equals(currentStatus)){ // id issues have these status, cannot assign staff as issue is already dealt with
                    JOptionPane.showMessageDialog(null, "For Customer Issues with status 'Done' or 'Closed' or 'Cancelled', it is not necessary to assign Staff.", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
                else{ // ii issue has status 'Open' or 'In Progress'
                    FileOperations file = new FileOperations();
                    ArrayList<Casting> issueRecords = file.searchRecord("CustomerIssue.txt", "In Progress", 2); // seraching for issues that are in progress
                    if (issueRecords.isEmpty()){ // if no issue in progress, all staff are free - staff can be assigned
                        if(!modifyStaff(rowIssue, rowStaff)){
                                JOptionPane.showMessageDialog(null, "Unsuccessfull attempt to assign staff.", "Information", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                    else{ // if there are issues that are in progress
                        Casting cast = new Casting();
                        ArrayList<Object> issueObjects = cast.convertRecordsToObjects(issueRecords, "CustomerIssue");
                        ArrayList<CustomerIssue> customerIssues = new ArrayList();

                        for (Object obj : issueObjects) {
                            if (obj instanceof CustomerIssue customerIssue) {
                                customerIssues.add(customerIssue);
                            } 
                            else {
                                JOptionPane.showMessageDialog(null, "Unexpected object type: " + obj.getClass().getName(), "Information", JOptionPane.INFORMATION_MESSAGE);
                            }
                        }

                        String newStaffID = tblStaff.getValueAt(rowStaff, 0).toString(); // getting ID of staff to be assigned
                        if(checkAvailabilityOfStaff(newStaffID, customerIssues)){ // checking the availability of the staff - if checkAvailabilityOfStaff = true, staff is free
                            if(!modifyStaff(rowIssue, rowStaff)){ // modifying the records accordingly
                                JOptionPane.showMessageDialog(null, "Unsuccessfull attempt to assign staff.", "Information", JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Staff is not available, please choose another staff.", "Information", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Please select a StaffID first.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select one IssueId first.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAssignStaffActionPerformed

    
    private void btnHomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomepageActionPerformed
        ManagerHomepage home = new ManagerHomepage();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnHomepageActionPerformed

    // static method to update table
    static void updateTable(JTable tbl,int row, int column, String value){
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setValueAt(value, row, column);
    }
    
   
    private void btnReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplyActionPerformed
        if (tblIssue.getSelectedRow() != -1){ // if an isssue is selected
            
            // retrieving necessary values
            String replyValue = tblIssue.getValueAt(tblIssue.getSelectedRow(), 5).toString();
            String IDValue = tblIssue.getValueAt(tblIssue.getSelectedRow(), 0).toString();
            if (!"".equals(txtReply.getText())){ // if user has entered the response
                FileOperations file = new FileOperations();
                String status = file.modify("CustomerIssue.txt", 5, replyValue, txtReply.getText(), IDValue , 0); // modifying the reply
                if ("Record updated successfully.".equals(status)){ // if modification successfull
                    int rowSelected = tblIssue.getSelectedRow();
                    updateTable(tblIssue, rowSelected, 5, txtReply.getText()); // updated row accordingly
                }
                else{
                    JOptionPane.showMessageDialog(null, status, "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Please enter response in the provided Text Area.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Select an IssueId First.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnReplyActionPerformed

    // method to modify the status of issue
    private boolean modifyStatus(String newStatus, int selectedRow){
        // retrieving necessary values
        String oldStatus = tblIssue.getValueAt(selectedRow, 2).toString();
        String customerIssueID = tblIssue.getValueAt(selectedRow, 0).toString();
        FileOperations file = new FileOperations();
        String status = file.modify("CustomerIssue.txt", 2, oldStatus, newStatus, customerIssueID, 0);// modifying the selected issue
        if ("Record updated successfully.".equals(status)){ // if modification is successfull
            updateTable(tblIssue, selectedRow, 2, newStatus); // updating the table
            return true; // modification successful - returning true
        }
        else{
            return false;
        }
    }
    
    private void btnChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStatusActionPerformed
        int selectedRow = tblIssue.getSelectedRow();
        if (selectedRow != -1){ // if issue has been selected
            if (cboChangeStatus.getSelectedIndex() != -1){ // if status has been updated
                String newStatus = cboChangeStatus.getSelectedItem().toString();
                if(!modifyStatus(newStatus, selectedRow)){ // calling method to modify the status - if method returns false - modifiaction failed
                    JOptionPane.showMessageDialog(null, "Unsuccessfull attempt to update status.", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Please select a Status first.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Select One IssueId First.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnChangeStatusActionPerformed

    // method to check availability of the staff chosen 
    private boolean checkAvailabilityOfStaff(String selectedID, ArrayList<CustomerIssue> issues){
        boolean checked = true;
        for (CustomerIssue i : issues){
            if (i.getStaffID().equals(selectedID)){ // if staffID of cutomerIssue is equal to staffID selected
                  checked = false; // staff not available    
            }
        }
        return checked;
    }
    
    // displaying the meaning of each status
    private void btnStatusMeaningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusMeaningActionPerformed
        JOptionPane.showMessageDialog(null, """
                                            Status Meaning :
                                            Open - The issue has been raised.
                                            In Progress - Work on the task has started.
                                            Done - The task has been completed.
                                            Closed - The task is closed and no further action is required.
                                            Cancelled - The task has been cancelled and will not be completed.""", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnStatusMeaningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerIssueManagementDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerIssueManagementDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerIssueManagementDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerIssueManagementDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerIssueManagementDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignStaff;
    private javax.swing.JButton btnChangeStatus;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnHomepage;
    private javax.swing.JButton btnReply;
    private javax.swing.JButton btnStatusMeaning;
    private javax.swing.JButton btnViewDescription;
    private javax.swing.JComboBox<String> cboChangeStatus;
    private javax.swing.JComboBox<String> cboStatusFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblIssue;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextArea txtIssueDescription;
    private javax.swing.JTextArea txtReply;
    // End of variables declaration//GEN-END:variables
}
