/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;


import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class SalesRecordDashboard extends javax.swing.JFrame {

    /**
     * Creates new form SalesRecordDashboard
     */
    public SalesRecordDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboSales = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnHomepage = new javax.swing.JButton();
        btnSummary = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(190, 209, 207));

        jPanel2.setBackground(new java.awt.Color(255, 247, 241));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("View Sales");

        jLabel2.setText("Choose type of filter to view sales records");

        cboSales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weekly", "Monthly", "Yearly" }));
        cboSales.setSelectedIndex(-1);
        cboSales.setSelectedItem(null);
        cboSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSalesActionPerformed(evt);
            }
        });

        btnSave.setText("Save Records");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnHomepage.setText("Homepage");
        btnHomepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomepageActionPerformed(evt);
            }
        });

        btnSummary.setText("Summary");
        btnSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cboSales, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnSummary)
                .addGap(18, 18, 18)
                .addComponent(btnHomepage)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave)
                    .addComponent(btnHomepage)
                    .addComponent(btnSummary))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Start Date", "End Date", "Amount"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    jScrollPane2.setViewportView(tblSales);

    jPanel3.setBackground(new java.awt.Color(255, 247, 241));

    jLabel4.setFont(new java.awt.Font("STLiti", 1, 24)); // NOI18N
    jLabel4.setText("Sales Records");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(338, 338, 338)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap(17, Short.MAX_VALUE)
            .addComponent(jLabel4)
            .addGap(15, 15, 15))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnHomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomepageActionPerformed
        ManagerHomepage home = new ManagerHomepage();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnHomepageActionPerformed

    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        DefaultTableModel table = (DefaultTableModel) tblSales.getModel();
        if (table.getRowCount() > 0){ // if sales have been calculated and displayed
            String type = cboSales.getSelectedItem().toString(); //fetching the type to be saved
            FileOperations file = new FileOperations();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            
            // switching between types displayed in the cboSales
            switch(type){
                case "Weekly":
                {
                    // clearing the files before saving record as writeToFile() 
                    // will append all the displayed records to the existing file
                    // to prevent this resaving records that have already been saved -
                    // clearing the file before writing to file
                    FileOperations.clearFile("WeeklySales.txt");
                    ArrayList<WeeklySales> weekly = new ArrayList<>();
                    for (int row = 0; row < table.getRowCount(); row++) {
                        //parsing displayed dates to correct LocalDate format using formatter
                        LocalDate startDate = LocalDate.parse(table.getValueAt(row, 0).toString(), formatter);
                        LocalDate endDate = LocalDate.parse(table.getValueAt(row, 1).toString(), formatter);
                        double amount = Double.parseDouble(table.getValueAt(row, 2).toString());
                        WeeklySales weeklySale= new WeeklySales(startDate, endDate, amount);
                        weekly.add(weeklySale);
                    }
                    String status = file.writeToFile("WeeklySales.txt", weekly);//writing records to file
                    JOptionPane.showMessageDialog(null, status, "Information", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
                case "Monthly":
                {
                    FileOperations.clearFile("MonthlySales.txt");
                    ArrayList<MonthlySales> monthly = new ArrayList<>();
                    for (int row = 0; row < table.getRowCount(); row++) {
                        LocalDate startDate = LocalDate.parse(table.getValueAt(row, 0).toString(), formatter);
                        LocalDate endDate = LocalDate.parse(table.getValueAt(row, 1).toString(), formatter);
                        double amount = Double.parseDouble(table.getValueAt(row, 2).toString());
                        MonthlySales monthlySale= new MonthlySales(startDate, endDate, amount);
                        monthly.add(monthlySale);
                    }
                    String status = file.writeToFile("MonthlySales.txt", monthly);
                    JOptionPane.showMessageDialog(null, status, "Information", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
                case "Yearly":
                {
                    FileOperations.clearFile("YearlySales.txt");
                    ArrayList<YearlySales> yearly = new ArrayList<>();
                    for (int row = 0; row < table.getRowCount(); row++) {
                        LocalDate startDate = LocalDate.parse(table.getValueAt(row, 0).toString(), formatter);
                        LocalDate endDate = LocalDate.parse(table.getValueAt(row, 1).toString(), formatter);
                        double amount = Double.parseDouble(table.getValueAt(row, 2).toString());
                        YearlySales yearlySale= new YearlySales(startDate, endDate, amount);
                        yearly.add(yearlySale);
                    }
                    String status = file.writeToFile("YearlySales.txt", yearly);
                    JOptionPane.showMessageDialog(null, status, "Information", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No sales record has been generated yet.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    //calculating and displaying records in table
    private void cboSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSalesActionPerformed
        int i = cboSales.getSelectedIndex();
        File checkFile = new File("Payment.txt");
        if (!checkFile.exists()) { //checking if Payment.txt exists before reading it
            JOptionPane.showMessageDialog(null, "No sales have been made until now.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else{ // Payment.txt exists
            FileOperations view = new FileOperations();
            ArrayList<Casting> paymentRecords = view.readFile("Payment.txt");//reading records in Payment.txt

            if (!paymentRecords.isEmpty()){ // checking if there are payments made yet
                Casting rec = new Casting();
                ArrayList<Object> records = rec.convertRecordsToObjects(paymentRecords,"Payment"); //casting method
                ArrayList<Payment> salesRecords = new ArrayList<>();

                // adding payment objects to the arraylist
                // validating if it is an instance of payment
                for (Object obj : records) {
                    if (obj instanceof Payment payment) {
                        salesRecords.add(payment);
                    } 
                    else {
                        JOptionPane.showMessageDialog(null, "Unexpected object type: " + obj.getClass().getName(), "Information", JOptionPane.INFORMATION_MESSAGE);
                    }
                }

                DefaultTableModel table = (DefaultTableModel) tblSales.getModel();
                table.setRowCount(0);//clearing table before adding new rows so that they do are not just appended again below existing rows

                // switching between types of sales obtained from cboSales
                switch (i){
                    case 0:
                    {
                        WeeklySales weekly = new WeeklySales();
                        ArrayList<WeeklySales> weeklyRecord = weekly.calculateAmounts(salesRecords); //calculating the weekly amounts with respective end and start dates
                        for (WeeklySales record : weeklyRecord){ // looping through arrayList created
                            table.addRow(new Object[]{ // creating the object using getters, and adding to the table
                                record.getStartDate(),
                                record.getEndDate(),
                                record.getAmount()
                            });
                        }
                        break;
                    }
                    case 1:
                    {
                        MonthlySales monthly = new MonthlySales();
                        ArrayList<MonthlySales> monthlyRecord = monthly.calculateAmounts(salesRecords);
                        for (MonthlySales record : monthlyRecord) {
                            table.addRow(new Object[]{
                                record.getStartDate(),
                                record.getEndDate(),
                                record.getAmount()
                            });
                        }
                        break;
                    }
                    case 2:
                    {
                        YearlySales yearly = new YearlySales();
                        ArrayList<YearlySales> yearlyRecord = yearly.calculateAmounts(salesRecords);
                        for (YearlySales record : yearlyRecord) {
                            table.addRow(new Object[]{
                                record.getStartDate(),
                                record.getEndDate(),
                                record.getAmount()
                            });
                        }
                        break;
                    }
                }//closing switch
            }
            else{
                JOptionPane.showMessageDialog(null, "No sales have been made until now.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_cboSalesActionPerformed

    private void btnSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSummaryActionPerformed
        SalesRecordSummary summary = new SalesRecordSummary();
        summary.setVisible(true);
        summary.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSummaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesRecordDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesRecordDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesRecordDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesRecordDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesRecordDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomepage;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSummary;
    private javax.swing.JComboBox<String> cboSales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSales;
    // End of variables declaration//GEN-END:variables
}
